### PR TITLE
Compressed Zip (golang 1.6)

### PR DESCRIPTION
**Pull request by mthenw**
That PR uses golang 1.6 features (`RegisterCompressor` on `writer`).

### CODE REVIEW

**Comment by jpillora** [comment]
Thanks for the PR, however I'm not sure how widespread 1.6 is yet and so this change could potentially break builds. This can be overcome though with [build constraints](https://golang.org/pkg/go/build/#hdr-Build_Constraints) and having two files with the first line as:
- `a_zip_go_old.go`: `// +build !go1.6`
- `a_zip_go_new.go`: `// +build go1.6`

And both of these files contain the function:

```
func newCompressedZipWriter(dst io.Writer, level int) *Archive
```

though only the `a_zip_go_new.go` file should use the new 1.6 zip API

**Comment by mthenw** [comment]
Updated, but there is one issue. `level` param can only be used in 1.6 because there is no option to change compression level of already registered compressor in <1.5. So the params differ between versions.

**Comment by jpillora** [comment]
Hey @mthenw, so the build tags are just specifying which files to include/ignore at build time, so we need is the version specific code to go into two extra files `a_zip_go_old.go` and `a_zip_go_new.go` and then `a_zip.go` should contain the bulk of the code.

I can do this change if you like, I'm just not sure when I'll get the chance...

**Comment by mthenw** [comment]
I'm not sure if we need that. `h.Method = zip.Deflate` can be set in both versions. The only difference is that in 1.5 there is no possibility to set compression level as the compressor is already registered. Or i'm missing something :)

**Comment by jpillora** [comment]
When I first looked into this, I noticed [1.6, `zip.Writer` implements `RegisterCompressor`](https://golang.org/pkg/archive/zip/#Writer), whereas in [1.5, `zip.Writer` does not](http://web.archive.org/web/20160128012918/https://golang.org/pkg/archive/zip/#Writer). A CI-run test suite that runs in 1.5 and in 1.6 would be helpful here!

**Comment by mthenw** [comment]
That's right. That's why I added build tags to archive.go. `czip.writer.RegisterCompressor` is only there.

**Comment by jpillora** [comment]
```
$ git status
On branch compressed
Your branch is up-to-date with 'mthenw/compressed'.
nothing to commit, working directory clean
$ go version
go version go1.5.3 darwin/amd64
$ go test
# github.com/jpillora/archive
./archive_go_old.go:17: Archive redeclared in this block
    previous declaration at ./archive_go_new.go:18
./archive_go_old.go:28: NewWriter redeclared in this block
    previous declaration at ./archive_go_new.go:29
./archive_go_old.go:53: NewTarWriter redeclared in this block
    previous declaration at ./archive_go_new.go:54
./archive_go_old.go:58: NewTarGzWriter redeclared in this block
    previous declaration at ./archive_go_new.go:59
./archive_go_old.go:63: NewZipWriter redeclared in this block
    previous declaration at ./archive_go_new.go:64
./archive_go_old.go:69: NewCompressedZipWriter redeclared in this block
    previous declaration at ./archive_go_new.go:70
./archive_go_old.go:80: (*Archive).AddBytes redeclared in this block
    previous declaration at ./archive_go_new.go:86
./archive_go_old.go:84: (*Archive).AddBytesMTime redeclared in this block
    previous declaration at ./archive_go_new.go:90
./archive_go_old.go:95: (*Archive).AddInfoFile redeclared in this block
    previous declaration at ./archive_go_new.go:101
./archive_go_old.go:104: (*Archive).AddFile redeclared in this block
    previous declaration at ./archive_go_new.go:110
./archive_go_old.go:104: too many errors
FAIL    github.com/jpillora/archive [build failed]
```

**Comment by mthenw** [comment]
ehh, there was no empty line after build tag. Could you check now.

**Comment by jpillora** [comment]
Merged, though we didn't need two copies of everything, just the 1.5/1.6 specific stuff needed to be split out. Kept the level param even in the Go version so things don't break for people moving from 1.5->1.6.

**Comment by mthenw** [comment]
gotcha, thanks!

**Pull request merged**
